# Generated by Django 3.2.7 on 2021-10-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Scriptures', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('Time_Entry', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
